### ISSUE TITLE
Make antic build-able outside of flint

### ISSUE THREAD

**Issue by SnarkBoojum** [flintlib/antic#2]
Hi,

can you provide a build system outside of FLINT ?

At one point perhaps distributions (Debian, Gentoo, Arch, Sage, etc) will want to package ANTIC, and having it in a self-contained way with just a dep on FLINT will be important.

Thanks,

Snark on #debian-science

**Comment by wbhart** [comment]
I believe we probably can. Arb did this, and it seems to work ok.

It's probably a bit early to be doing this yet. There's a lot more
functionality we want to add before getting really serious there. But
eventually we might do this.

Bill.

**Comment by SnarkBoojum** [comment]
Yes, arb did this, and yes it works. If only it had soname version numbering, I could package it for Debian! [Note: I provided a patch for that, so I'm not just asking things around : I actually help get things done whenever I can]

**Comment by videlec** [comment]
Beyond distrubtions, an independent build system would also be useful for me (https://github.com/videlec/e-antic)!

**Comment by wbhart** [comment]
We have decided we want to do this. We simply need to find the time to do
it.

**Comment by videlec** [comment]
done in #18
