### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by thofma** [flintlib/antic#20]
Since the recent changes in #18 and #19 I cannot build antic anymore:

```.../antic/nf.h:30:25: fatal error: flint/flint.h: No such file or directory```

@wbhart I would like to update the antic version of Nemo but this is blocking it.

**Comment by wbhart** [comment]
Antic now has its own build system. It works just like Arb.

**Comment by thofma** [comment]
So it was the intention to break the --extension build?

**Comment by wbhart** [comment]
Yes, Arb also doesn't work as an extension build. It's not really avoidable.
