### ISSUE TITLE
flint2 isn't the only dependency

### ISSUE THREAD

**Issue by yurivict** [flintlib/antic#22]
README says ```The only dependency at present is flint2``` which is wrong. ```gmp``` and ```mpfr``` are also dependencies.

**Comment by wbhart** [comment]
This is not a helpful distinction. Should the dependencies of Flint ever change, so would the dependencies of Antic, by your definition. And it wholly depends on whether you are talking about library, symbol, or build dependencies.

**Comment by wbhart** [comment]
Just to clarify this point a little. Currently the build system for Antic was taken from Arb, which has an actual dependency on MPIR or GMP and on MPFR. To my recollection, Antic has no hard dependence on either, even though the build system requires you to tell it where they are. We have often thought about removing the dependence of Flint on MPFR, at which point Antic would have no dependence on MPFR.

The statement that was there in the README was written when there was no independent build system for Antic. It was built as a Flint extension library, which meant that it really only had Flint as a dependency. One could argue that this is not currently true. But note that there are no official releases of Antic at the moment. You are looking at a random point in its development before the first release.

**Comment by yurivict** [comment]
libantic.so directly links to all three libraries.
