### ISSUE TITLE
Is there a released tarball?

### ISSUE THREAD

**Issue by saraedum** [flintlib/antic#31]
I would like to package ANTIC for conda-forge. Are there any releases (planned) so that packagers could use an official tarball to build from?

**Comment by saraedum** [comment]
cc @videlec

**Comment by wbhart** [comment]
No, at the moment there are no official releases. However, I think Antic is pretty stable and we could make a release. I intended to do this late last year and never really got around to it.

I'll have a quick check later this week what state things are in, and if everything is ok, I'll tag an official release.

**Comment by wbhart** [comment]
I have enabled travis-CI and cleaned up some of the paperwork.

There have been no objections to doing a release. It will actually be version 0.2. Version 0.1 was released back in 2013 or so, but was not tagged (since there were many bugs, I'm not going to get too worked up about that).

I should be able to tag a release today or tomorrow, I think.

**Comment by wbhart** [comment]
I tagged v0.2.

**Comment by saraedum** [comment]
Unfortunately, antic requires an unreleased version of FLINT, namely it uses `fmpq_poly_get_coeff_fmpz` and `_fmpq_poly_resultant_div`.

**Comment by wbhart** [comment]
That's correct. Unfortunately I am the only person who can really work on a Flint release and there remain many very difficult tickets before we can do so.

Our plan at this stage is to do that work in the first three months of next year (assuming no other unscheduled interruptions). I know it's not ideal, but there is only one of me, and he is quite busy until the end of the year with another project.

**Comment by fingolfin** [comment]
@saraedum In case it is stillrelevant for you: there is now a new antic release available from https://github.com/wbhart/antic/releases/tag/v0.2.1

**Comment by saraedum** [comment]
Thanks for the ping. I started packaging antic here: https://github.com/conda-forge/staged-recipes/pull/11929
