### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by saraedum** [flintlib/antic#43]
The license file that was just added says LGPL2.1 but most files say GPL2+ in their headers. Would you mind adding something to the readme that clarifies the license situation? Is it LGPL2.1-or-later?

**Comment by saraedum** [comment]
And there's also a gpl-2.0.txt in the repository.

**Comment by wbhart** [comment]
Ah yeah, we'll need to run through with a script. It's changing to LGPL. The LGPL is an addendum to the GPL though, so it's right that the gpl-2.0.txt is in there.

**Comment by thofma** [comment]
FWIW, according to the headers, lots of these files belong to arb or flint. Might have to adjust that too.

**Comment by saraedum** [comment]
> The LGPL is an addendum to the GPL though, so it's right that the gpl-2.0.txt is in there.

But isn't the LICENSE file self-contained already? It's a bit confusing right now :)

**Comment by wbhart** [comment]
No it's not self contained.

https://www.gnu.org/licenses/gpl-howto.en.html

Anyhow, it is now LGPL v2.1+
