### ISSUE TITLE
Out-of-tree builds

### ISSUE THREAD

**Issue by saraedum** [flintlib/antic#46]
Is it possible to build antic out-of-tree? (i.e., the equivalent of `mkdir build`, `cd build`, `../antic/configure`, `make`)

It seems that `./configure` wants to run in the source tree. I could create a PR that autoconfiscates antic if that's helpful.

**Comment by wbhart** [comment]
No, neither Flint not Antic build out of tree at present. There is an open ticket for the Flint build system to add that one day, but it's a big job.

Autoconf is a rather big hammer to bash that nail with, and we don't want a third build system for Flint, so I don't think it is worth doing that.

**Comment by mahrud** [comment]
The CMake build of Flint supports out-of-tree builds.
