### ISSUE TITLE
nf_elem_reduce sometimes canonicalises and sometimes doesn't

### ISSUE THREAD

**Issue by fredrik-johansson** [flintlib/antic#55]
nf_elem_reduce canonicalises its input when the field is quadratic or higher, but doesn't canonicalise when the field is linear.

This should probably be made consistent. Otherwise, users that want to perform reduction + canonicalisation will either have to perform the canonicalisation twice or make a case distinction depending on whether the field is linear.

The current behavior is not documented, in any case.

**Comment by wbhart** [comment]
This looks to be a bug. The code does nothing in the case of a linear field as there is no reduction to be done. Instead it should unconditionally call the canonicalisation as it does in the other cases. At least this is an easy fix.

**Comment by fredrik-johansson** [comment]
Thanks!
