### ISSUE TITLE
Compatibility with flint 2.6

### ISSUE THREAD

**Issue by saraedum** [flintlib/antic#57]
In https://github.com/wbhart/antic/commit/2d6a93c1b34d545abf98f1b2d6fe85ecf281b7a9 antic was adapted to API changes in flint 2.7. In e-antic we would like to support both flint 2.6 and 2.7 to make upgrading easier.

I could add a few #ifdefs to make antic work with flint 2.6 and 2.7. Should I go ahead and create a Pull Request?

**Comment by saraedum** [comment]
cc @videlec

**Comment by wbhart** [comment]
That's fine, but please be aware that we do not intend to maintain the flint-2.6 version of flint or antic.
