### ISSUE TITLE
The test for `mod_fmpz` fails

### ISSUE THREAD

**Issue by albinahlback** [flintlib/antic#74]
Output:
```
mod_fmpz....FAIL: Reducing without denominator
f = 1/3*x^3+1/3*x-1/3
a = 0
b = 0
c = 0
n = 39613779025677300323867164673
```

Fails both on FLINT branches `trunk` and `flint-2.8`, with Antic being current state of `trunk`.

**Comment by albinahlback** [comment]
Can you verify that you get the same result, @thofma?

**Comment by thofma** [comment]
I don't have the setup to build flint/antic locally at the moment. Could you check @tthsqe12?

**Comment by tthsqe12** [comment]
I get the exact same failure.

**Comment by albinahlback** [comment]
I've tried to go back in the commits to the beginning of last year, but the test still fails.

**Comment by albinahlback** [comment]
Seems to be this line
https://github.com/wbhart/antic/blob/e6f8bf1b640f7d1d5370eff542e23aa0ba80dd99/nf_elem/mod_fmpz.c#L86
that causes the problem: The only time it is ran is when the test fails.

**Comment by wbhart** [comment]
What is wrong with the line? Elsewhere you seemed to indicate it could not be causing the issue.

**Comment by albinahlback** [comment]
Executing that line resulted in an error, but that was resolved with the PR. As I noticed, it was no problem with the function in itself, but rather one of its dependencies. Sorry for the confusion.

**Comment by wbhart** [comment]
Thanks for clarifying.
