### ISSUE TITLE
t-init-clear segfault with flint 2.9.0

### ISSUE THREAD

**Issue by SnarkBoojum** [flintlib/antic#79]
Since I updated flint to 2.9.0 in Debian, antic [broke](https://tracker.debian.org/pkg/flint) (see the red Regression links):
```
make: Entering directory '/tmp/autopkgtest-lxc.ahzsw60a/downtmp/autopkgtest_tmp/tests/nf'
cc -I/usr/include/antic    t-init_clear.c  -lantic -lflint -lgmp -o t-init_clear
+-+-+-+ t-init_clear +-+-+-+
init/clear....Segmentation fault
```
is it a known issue?

**Comment by tthsqe12** [comment]
From what I can see just looking at amd64, flint version 2.8.5 is being used. Flint 2.9.0 has one relevent binary incompatibility that can be causing a segfault. However, antic 0.2.1 should work fine with either flint 2.8.5 or flint 2.9.0. So maybe that setup is using 2.9.0 headers and 2.8.5 binaries, or vice-versa?

**Comment by SnarkBoojum** [comment]
It was worse than that : the -dev of 2.9.0 was used for the headers and the not-dev from 2.8.5 was used for the linking... It's strange it didn't break more than that! The problem was that building the lib uses unusual tricks (not autotools, strange rpath magic...). Hopefully my upload 2.9.0-4 should fix everything.

Closing -- I'll reopen an issue if it turns out something wasn't my fault in the mess... Sorry for the inconvenience.
