### ISSUE TITLE
please document fmpz[3] for qnf_elem

### ISSUE THREAD

**Issue by videlec** [flintlib/antic#9]
To store a quadratic element only two integers are needed for the numerator. But this is declared as

```
typedef struct /* element of a quadratic number field */
{
   fmpz num[3];
   fmpz_t den;
} qnf_elem_struct;
typedef qnf_elem_struct qnf_elem_t[1];
```

It would better be documented what does the third term in the numerator is used for (and if we are free to use it as a temporary variable).

**Comment by wbhart** [comment]
It's used as a temporary for multiplication.
